language: rust

rust:
  - stable
  - nightly

# TODO: Cache cargo symbols for faster build
#cache: cargo

install:
  - PATH=$PATH:/home/travis/.cargo/bin
  - cargo install cargo-cmd
  - cargo cmd deps

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo cmd test
